import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/molecules/NavBar/NavBar'
import Footer from '@/components/molecules/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='container bg-main-bg'>
        <Navbar name='Oak' />
        {children}
        <Footer />
      </body>
    </html>
  )
}
